// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js";
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js";

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default:
    | React.ComponentType<{ params: Promise<ParamMap[Route]> } & any>
    | ((
        props: { params: Promise<ParamMap[Route]> } & any
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default:
    | React.ComponentType<LayoutProps<Route>>
    | ((
        props: LayoutProps<Route>
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

// Validate ../../../app/app/assets/id/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/assets/id">> =
    Specific;
  const handler = {} as typeof import("../../(app)/assets/id/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../app/app/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/assets">> = Specific;
  const handler = {} as typeof import("../../(app)/assets/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../app/app/invest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/invest">> = Specific;
  const handler = {} as typeof import("../../(app)/invest/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific;
  const handler = {} as typeof import("../../(app)/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../app/app/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/portfolio">> =
    Specific;
  const handler = {} as typeof import("../../(app)/portfolio/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../app/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/profile">> = Specific;
  const handler = {} as typeof import("../../(app)/profile/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../app/app/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/wallet">> = Specific;
  const handler = {} as typeof import("../../(app)/wallet/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../app/auth/investor/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/investor/login">> =
    Specific;
  const handler = {} as typeof import("../investor/login/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../app/auth/investor/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/investor/signup">> =
    Specific;
  const handler = {} as typeof import("../investor/signup/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific;
  const handler = {} as typeof import("../../(public)/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../app/partner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner">> = Specific;
  const handler = {} as typeof import("../../(app)/partner/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific;
  const handler = {} as typeof import("../../(app)/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific;
  const handler = {} as typeof import("../../../app/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}
